name: collect-aws-metadata build + test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running in response to ${{ github.event_name }}"

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.1
      
      - name: Set up Go path
        run: echo "${{ runner.temp }}/go/bin" >> $GITHUB_PATH
      
      - name: Test
        run: make test
