name: collect-aws-metadata build + test
on: [push]  # all push to any branch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running in response to ${{ github.event_name }}"

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: "Setup Go"
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      
      - name: "Test"
        run: make test-100pct

      - name: "Build"
        run: make

      - name: "Artifact"
        uses: actions/upload-artifact@v2
        with:
          name: collect-aws-metadata
          path: ./collect-aws-metadata

      # - name: "tag release"
