name: collect-aws-metadata build + test
on: [push]  # all push to any branch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running in response to ${{ github.event_name }}"

      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # all branches and tags; needed for version string

      - name: "Setup Go"
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      
      - name: "Test"
        run: make test-100pct

      - name: "Build"
        run: make tarball

      - name: "Describe version"
        run: |
          echo "release_version=$(tools/describe-version)" | tee -a $GITHUB_ENV

      - name: "Artifact"
        uses: actions/upload-artifact@v2
        with:
          name: collect-aws-metadata-${{ env.release_version }}.tar.gz
          path: ./collect-aws-metadata-${{ env.release_version }}.tar.gz


  ## release:
  ##   runs-on: ubuntu-latest
  ##   steps:
  ##     - name: "tag release"
